export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_TYPES = [
  CREATE_TASK,
  CREATE_TASK_SUCCESS,
  CREATE_TASK_ERROR
];

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_TYPES = [
  DELETE_TASK,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_ERROR
];

export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_TYPES = [
  FETCH_TASKS,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_ERROR
];

export const UPDATE_TASK = 'UPDATE_TASK';
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_TYPES = [
  UPDATE_TASK,
  UPDATE_TASK_SUCCESS,
  UPDATE_TASK_ERROR
];
